In [1]:
import pandas as pd

In [2]:
data=[['apple','bear','rice','chicken'],
      ['apple','bear','rice'],
      ['apple','bear'],
      ['apple','pear'],
      ['apple','bear','rice','chicken'],
      ['apple','bear','rice'],
      ['apple','bear'],
      ['apple','pear']]

### Transaction encoder for creating structured data

In [6]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.23.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.1-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   - -------------------------------------- 0.1/1.4 MB 252.2 kB/s eta 0:00:06
   - -------------------------------------- 0.1/1.4 MB 245.8 kB/s eta 0:00:06
   -- ------------------------------------- 0.1/1.4 MB 275.8 kB/s eta 0:00:05
   --- ------------------------------------ 0.1/1.4 MB 297.7 kB/s eta 0:00:05
   --- ------------------------------------ 0.1/1.4 MB 288.1 kB/s eta 0:00:05
   --- ------------------------------------ 0.1/1.4 MB 293.9 kB/s eta 0:00:05
   ---- ----------------------------------- 0.2/1.4 MB 286.7 kB/s eta 0:00:05
   ---- ----------------------------------- 0.2/1.4 MB 308.5 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.4 MB 327.5 kB/s eta 0:00:04
   ------ --------------------------------- 0.2/1.4 MB 327.8 kB/s eta 0:00:04
   ------- -------------------------------- 0.3/1.4 MB 349.6 kB/s eta 0:00:04
   ------- -------------------------------- 0.3/1.4 MB 370.3 kB/s eta 0:00:04
   ------- -------------------------------- 0.3/1.4 MB 368.6 kB/s eta 0:00:04
   -------- ------------------------------- 0.3/1.4 MB 371.0 kB/s eta 0:00:04
   -------- ------------------------------- 0.3/1.4 MB 371.0 kB/s eta 0:00:04
   --------- ------------------------------ 0.3/1.4 MB 367.8 kB/s eta 0:00:04
   ---------- ----------------------------- 0.4/1.4 MB 363.9 kB/s eta 0:00:03
   ---------- ----------------------------- 0.4/1.4 MB 367.5 kB/s eta 0:00:03
   ----------- ---------------------------- 0.4/1.4 MB 380.0 kB/s eta 0:00:03
   ----------- ---------------------------- 0.4/1.4 MB 380.0 kB/s eta 0:00:03
   ------------ --------------------------- 0.5/1.4 MB 375.7 kB/s eta 0:00:03
   ------------- -------------------------- 0.5/1.4 MB 381.4 kB/s eta 0:00:03
   ------------- -------------------------- 0.5/1.4 MB 383.7 kB/s eta 0:00:03
   -------------- ------------------------- 0.5/1.4 MB 394.8 kB/s eta 0:00:03
   --------------- ------------------------ 0.6/1.4 MB 399.1 kB/s eta 0:00:03
   --------------- ------------------------ 0.6/1.4 MB 397.5 kB/s eta 0:00:03
   ---------------- ----------------------- 0.6/1.4 MB 404.3 kB/s eta 0:00:03
   ---------------- ----------------------- 0.6/1.4 MB 406.8 kB/s eta 0:00:03
   ------------------ --------------------- 0.7/1.4 MB 421.4 kB/s eta 0:00:02
   ------------------ --------------------- 0.7/1.4 MB 424.0 kB/s eta 0:00:02
   ------------------- -------------------- 0.7/1.4 MB 430.6 kB/s eta 0:00:02
   -------------------- ------------------- 0.7/1.4 MB 436.8 kB/s eta 0:00:02
   --------------------- ------------------ 0.8/1.4 MB 452.7 kB/s eta 0:00:02
   ------------------------ --------------- 0.9/1.4 MB 478.7 kB/s eta 0:00:02
   ------------------------ --------------- 0.9/1.4 MB 483.1 kB/s eta 0:00:02
   ------------------------- -------------- 0.9/1.4 MB 480.6 kB/s eta 0:00:02
   -------------------------- ------------- 1.0/1.4 MB 491.4 kB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.4 MB 499.3 kB/s eta 0:00:01
   ---------------------------- ----------- 1.0/1.4 MB 504.2 kB/s eta 0:00:01
   ----------------------------- ---------- 1.1/1.4 MB 511.3 kB/s eta 0:00:01
   ------------------------------ --------- 1.1/1.4 MB 520.4 kB/s eta 0:00:01
   ------------------------------- -------- 1.2/1.4 MB 528.0 kB/s eta 0:00:01
   --------------------------------- ------ 1.2/1.4 MB 539.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.2/1.4 MB 528.7 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.4 MB 540.1 kB/s eta 0:00:01
   ----------------------------------- ---- 1.3/1.4 MB 542.4 kB/s eta 0:00:01
   ------------------------------------ --- 1.3/1.4 MB 541.2 kB/s eta 0:00:01
   ------------------------------------- -- 1.4/1.4 MB 551.0 kB/s eta 0:00:01
   -------------------------------------- - 1.4/1.4 MB 553.5 kB/s eta 0:00:01
   ---------------------------------------  1.4/1.4 MB 562.9 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 558.3 kB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.1

In [14]:
from mlxtend.preprocessing import TransactionEncoder

In [15]:
te=TransactionEncoder()

In [16]:
df_enc=te.fit_transform(data)

In [17]:
df_enc

array([[ True,  True,  True, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False, False],
       [ True, False, False,  True, False],
       [ True,  True,  True, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False, False, False],
       [ True, False, False,  True, False]])

In [18]:
te.columns_

['apple', 'bear', 'chicken', 'pear', 'rice']

In [22]:
df=pd.DataFrame(df_enc,columns= te.columns_)

In [23]:
df

   apple   bear  chicken   pear   rice
0   True   True     True  False   True
1   True   True    False  False   True
2   True   True    False  False  False
3   True  False    False   True  False
4   True   True     True  False   True
5   True   True    False  False   True
6   True   True    False  False  False
7   True  False    False   True  False

## Generate frequent itemset

In [26]:
from mlxtend.frequent_patterns import apriori

In [27]:
freq_itemset =apriori(df,min_support=0.25,use_colnames=True)

In [28]:
freq_itemset

    support                      itemsets
0      1.00                       (apple)
1      0.75                        (bear)
2      0.25                     (chicken)
3      0.25                        (pear)
4      0.50                        (rice)
5      0.75                 (apple, bear)
6      0.25              (apple, chicken)
7      0.25                 (pear, apple)
8      0.50                 (rice, apple)
9      0.25               (bear, chicken)
10     0.50                  (rice, bear)
11     0.25               (rice, chicken)
12     0.25        (apple, bear, chicken)
13     0.50           (rice, apple, bear)
14     0.25        (rice, apple, chicken)
15     0.25         (rice, bear, chicken)
16     0.25  (rice, apple, bear, chicken)

### generate the association rules

In [29]:
from mlxtend.frequent_patterns import association_rules

In [31]:
rules=association_rules(freq_itemset,metric='confidence',min_threshold=0.50)

In [32]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(apple),(bear),1.00,0.75,0.75,0.750000,1.000000,0.0000,1.0,0.000000
1,(bear),(apple),0.75,1.00,0.75,1.000000,1.000000,0.0000,inf,0.000000
2,(chicken),(apple),0.25,1.00,0.25,1.000000,1.000000,0.0000,inf,0.000000
3,(pear),(apple),0.25,1.00,0.25,1.000000,1.000000,0.0000,inf,0.000000
4,(rice),(apple),0.50,1.00,0.50,1.000000,1.000000,0.0000,inf,0.000000
5,(apple),(rice),1.00,0.50,0.50,0.500000,1.000000,0.0000,1.0,0.000000
6,(chicken),(bear),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf,0.333333
7,(rice),(bear),0.50,0.75,0.50,1.000000,1.333333,0.1250,inf,0.500000
8,(bear),(rice),0.75,0.50,0.50,0.666667,1.333333,0.1250,1.5,1.000000
9,(rice),(chicken),0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
10,(chicken),(rice),0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
11,"(apple, chicken)",(bear),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf,0.333333
12,"(bear, chicken)",(apple),0.25,1.00,0.25,1.000000,1.000000,0.0000,inf,0.000000
13,(chicken),"(apple, bear)",0.25,0.75,0.25,1.000000,1.333333,0.0625,inf,0.333333
14,"(rice, apple)",(bear),0.50,0.75,0.50,1.000000,1.333333,0.1250,inf,0.500000
15,"(rice, bear)",(apple),0.50,1.00,0.50,1.000000,1.000000,0.0000,inf,0.000000
16,"(apple, bear)",(rice),0.75,0.50,0.50,0.666667,1.333333,0.1250,1.5,1.000000
17,(rice),"(apple, bear)",0.50,0.75,0.50,1.000000,1.333333,0.1250,inf,0.500000
18,(apple),"(rice, bear)",1.00,0.50,0.50,0.500000,1.000000,0.0000,1.0,0.000000
19,(bear),"(rice, apple)",0.75,0.50,0.50,0.666667,1.333333,0.1250,1.5,1.000000
20,"(rice, apple)",(chicken),0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
21,"(rice, chicken)",(apple),0.25,1.00,0.25,1.000000,1.000000,0.0000,inf,0.000000
22,"(apple, chicken)",(rice),0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
23,(rice),"(apple, chicken)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
24,(chicken),"(rice, apple)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
25,"(rice, bear)",(chicken),0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
26,"(rice, chicken)",(bear),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf,0.333333
27,"(bear, chicken)",(rice),0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
28,(rice),"(bear, chicken)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
29,(chicken),"(rice, bear)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
30,"(rice, apple, bear)",(chicken),0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
31,"(rice, apple, chicken)",(bear),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf,0.333333
32,"(rice, bear, chicken)",(apple),0.25,1.00,0.25,1.000000,1.000000,0.0000,inf,0.000000
33,"(apple, bear, chicken)",(rice),0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
34,"(rice, apple)","(bear, chicken)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
35,"(rice, bear)","(apple, chicken)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
36,"(rice, chicken)","(apple, bear)",0.25,0.75,0.25,1.000000,1.333333,0.0625,inf,0.333333
37,"(apple, chicken)","(rice, bear)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
38,"(bear, chicken)","(rice, apple)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667
39,(rice),"(apple, bear, chicken)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.5,1.000000
40,(chicken),"(rice, apple, bear)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf,0.666667

In [38]:
rules=rules[['antecedents','consequents','support','confidence']]

In [39]:
rules

               antecedents             consequents  support  confidence
0                  (apple)                  (bear)     0.75    0.750000
1                   (bear)                 (apple)     0.75    1.000000
2                (chicken)                 (apple)     0.25    1.000000
3                   (pear)                 (apple)     0.25    1.000000
4                   (rice)                 (apple)     0.50    1.000000
5                  (apple)                  (rice)     0.50    0.500000
6                (chicken)                  (bear)     0.25    1.000000
7                   (rice)                  (bear)     0.50    1.000000
8                   (bear)                  (rice)     0.50    0.666667
9                   (rice)               (chicken)     0.25    0.500000
10               (chicken)                  (rice)     0.25    1.000000
11        (apple, chicken)                  (bear)     0.25    1.000000
12         (bear, chicken)                 (apple)     0.25    1.000000
13               (chicken)           (apple, bear)     0.25    1.000000
14           (rice, apple)                  (bear)     0.50    1.000000
15            (rice, bear)                 (apple)     0.50    1.000000
16           (apple, bear)                  (rice)     0.50    0.666667
17                  (rice)           (apple, bear)     0.50    1.000000
18                 (apple)            (rice, bear)     0.50    0.500000
19                  (bear)           (rice, apple)     0.50    0.666667
20           (rice, apple)               (chicken)     0.25    0.500000
21         (rice, chicken)                 (apple)     0.25    1.000000
22        (apple, chicken)                  (rice)     0.25    1.000000
23                  (rice)        (apple, chicken)     0.25    0.500000
24               (chicken)           (rice, apple)     0.25    1.000000
25            (rice, bear)               (chicken)     0.25    0.500000
26         (rice, chicken)                  (bear)     0.25    1.000000
27         (bear, chicken)                  (rice)     0.25    1.000000
28                  (rice)         (bear, chicken)     0.25    0.500000
29               (chicken)            (rice, bear)     0.25    1.000000
30     (rice, apple, bear)               (chicken)     0.25    0.500000
31  (rice, apple, chicken)                  (bear)     0.25    1.000000
32   (rice, bear, chicken)                 (apple)     0.25    1.000000
33  (apple, bear, chicken)                  (rice)     0.25    1.000000
34           (rice, apple)         (bear, chicken)     0.25    0.500000
35            (rice, bear)        (apple, chicken)     0.25    0.500000
36         (rice, chicken)           (apple, bear)     0.25    1.000000
37        (apple, chicken)            (rice, bear)     0.25    1.000000
38         (bear, chicken)           (rice, apple)     0.25    1.000000
39                  (rice)  (apple, bear, chicken)     0.25    0.500000
40               (chicken)     (rice, apple, bear)     0.25    1.000000

### Extract using condition

In [41]:
rules[(rules['confidence']>0.5)&(rules['support']>0.25)]

      antecedents    consequents  support  confidence
0         (apple)         (bear)     0.75    0.750000
1          (bear)        (apple)     0.75    1.000000
4          (rice)        (apple)     0.50    1.000000
7          (rice)         (bear)     0.50    1.000000
8          (bear)         (rice)     0.50    0.666667
14  (rice, apple)         (bear)     0.50    1.000000
15   (rice, bear)        (apple)     0.50    1.000000
16  (apple, bear)         (rice)     0.50    0.666667
17         (rice)  (apple, bear)     0.50    1.000000
19         (bear)  (rice, apple)     0.50    0.666667

### Recomendation

In [43]:
rules[rules['antecedents']=={'rice'}]

   antecedents             consequents  support  confidence
4       (rice)                 (apple)     0.50         1.0
7       (rice)                  (bear)     0.50         1.0
9       (rice)               (chicken)     0.25         0.5
17      (rice)           (apple, bear)     0.50         1.0
23      (rice)        (apple, chicken)     0.25         0.5
28      (rice)         (bear, chicken)     0.25         0.5
39      (rice)  (apple, bear, chicken)     0.25         0.5

### Sort

In [45]:
rules.sort_values(by='confidence',ascending=False);

In [46]:
# Save the Rules

rules.to_csv('rules_csv',index=False)